server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1


spring:
  profiles:
    active: dev
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000 # 请求的文件大小限制为500kb
      max-request-size: 512000
  data:
    mongodb:
      database: sun
      username: root
      password: "12345678"
      host: 10.196.80.3
      port: 27017
      authentication-database: admin
#      uri: mongodb://root:12345678@10.196.247.227:27017/sun

# Minio 配置

minio:
  endpoint:  http://127.0.0.1:9000 #对象存储服务的URL
  accessKey: minioadmin #Access key账户 写账号也可以
  secretKey: minioadmin #Secret key密码
  bucketName: sun # 桶名称
  expire: 7200 # 过期时间

#百度人脸识别配置
baidu:
  face:
    appId: "118475429"
    apiKey: "YXHGRjqz7ASnUVnxXa2L2aug"
    secretKey: "zSWYf4Oa8dzcRkj2LnnfxuHNp2Nwxiz3"



