server:
#  port: 8002
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1


spring:
  profiles:
    active: dev
  application:
    name: service-article-html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      database: sun
      username: root
      password: "12345678"
      host: 10.196.80.3
      port: 27017
      authentication-database: admin
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 10.196.80.3
    port: 5672
    username: admin
    password: 12345678
    virtual-host: sun



mybatis:
  type-aliases-package: com.sun.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.sun.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

#定义freemarker生成的html位置
freemarker:
  html:
    target: /Users/horizon/Desktop/project/sun-dev/freemarker_html
    article: /Library/apache-tomcat-10.1.39/webapps/sun/portal/a

#百度内容审核
baidu:
  detection:
    appId: "118518231"
    apiKey: "1ux4Ln1rNwTMtE8Kg203aPRy"
    secretKey: "NNcFj4EMMaEp2o2Z07slxAS9npQsGDy2"