server:
#  port: 8001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1


spring:
  profiles:
    active: dev
  application:
    name: service-article
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/horizon
    username: root
    password: 12345678
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      database: sun
      username: root
      password: "12345678"
      host: 10.196.92.215
      port: 27017
      authentication-database: admin
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 10.196.92.215
#    host: localhost
    port: 5672
    username: admin
    password: 12345678
    virtual-host: sun



mybatis:
  type-aliases-package: com.sun.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.sun.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

#定义freemarker生成的html位置
freemarker:
  html:
    target: /Users/horizon/Desktop/project/sun-dev/freemarker_html
    article: /Library/apache-tomcat-10.1.39/webapps/sun/portal/a

#百度内容审核
baidu:
  detection:
    appId: "118518231"
    apiKey: "1ux4Ln1rNwTMtE8Kg203aPRy"
    secretKey: "NNcFj4EMMaEp2o2Z07slxAS9npQsGDy2"

alibaba:
  api: "sk-5051014b247e49378a198ad1b33e48ca"

#eureka:
#  instance:
#    instance-id: ${eureka.server.loc}:${server.port}
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 3  # 调整微服务和注册中心的心跳
#    lease-expiration-duration-in-seconds: 5  # eureka距离最近的一次心跳等待的剔除的时间，默认90s
#  server:
#    hostname: eureka
#    port: 6500
#    loc: article.cun.com
#  client:
#    # 是否要把当前的eureka server注册到自己
#    register-with-eureka: true
#    # 从注册中心获得检索服务实例，server没有必要，直接false
#    fetch-registry: true
#    service-url:
##      defaultZone: http://eureka-cluster-6501:6501/eureka/, http://eureka-cluster-6502:6502/eureka/
#      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
