server:
#  port: 8005
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1


spring:
  profiles:
    active: dev
  application:
    name: service-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/horizon
    username: root
    password: 12345678
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      database: sun
      username: root
      password: "12345678"
      host: 10.196.80.3
      port: 27017
      authentication-database: admin


mybatis:
  type-aliases-package: com.sun.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.sun.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

#百度人脸识别配置
baidu:
  face:
    appId: "118475429"
    apiKey: "YXHGRjqz7ASnUVnxXa2L2aug"
    secretKey: "zSWYf4Oa8dzcRkj2LnnfxuHNp2Nwxiz3"