server:
  port: ${port:6502}
  tomcat:
    uri-encoding: UTF-8

management:
  health:
    redis:
      enabled: false

spring:
  application:
    name: springcloud-eureka-cluster


eureka:
  instance:
    hostname: eureka-cluster-${port:6502}
  other-node-port2: ${port2:6501}
  client:
    # 是否要把当前的eureka server注册到自己
    register-with-eureka: false
    # 从注册中心获得检索服务实例，server没有必要，直接false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-cluster-${eureka.other-node-port2}:${eureka.other-node-port2}/eureka/




